apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

components:
  - ../../../components/cks-node-cache

patches:
  - target:
      kind: LeaderWorkerSet
      name: inkling
    patch: |-
      - op: test
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/env/0/name
        value: MODEL
      - op: replace
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/env/0/value
        value: Qwen/Qwen3.8-27B-FP8
