apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

components:
  - ../../../components/gke-rdma-networking
  - ../../../components/gke-node-cache
  - ../../../components/gke-placement
  - ../../../components/gke-nccl-plugins
